from __future__ import annotations

from winros.vla.types import StructuredCommand, VLAProvider, VLARequest


class RuleBasedVLAProvider:
    name = "rules"
    description = "Small deterministic provider for interface tests and dry-run demos."

    def generate(self, request: VLARequest) -> StructuredCommand:
        text = request.instruction.lower()
        if any(token in text for token in ("stop", "halt", "pause", "freeze")):
            return StructuredCommand(
                robot=request.robot,
                command_type="mode",
                target={"mode": "stop"},
                source_provider=self.name,
                confidence=0.95,
                notes=("Generated by a deterministic safety-first provider.",),
            )
        if any(token in text for token in ("stairs", "stair", "steps")):
            return StructuredCommand(
                robot=request.robot,
                command_type="locomotion",
                target={"velocity_x": 0.25, "velocity_y": 0.0, "yaw_rate": 0.0, "terrain": "stairs"},
                source_provider=self.name,
                confidence=0.66,
                notes=("Command must pass terrain and fall-risk validation before hardware.",),
            )
        if any(token in text for token in ("run", "fast")):
            return StructuredCommand(
                robot=request.robot,
                command_type="locomotion",
                target={"velocity_x": 0.8, "velocity_y": 0.0, "yaw_rate": 0.0},
                source_provider=self.name,
                confidence=0.62,
                notes=("Fast commands should stay in simulation until policy limits are verified.",),
            )
        if any(token in text for token in ("walk", "forward", "move")):
            return StructuredCommand(
                robot=request.robot,
                command_type="locomotion",
                target={"velocity_x": 0.35, "velocity_y": 0.0, "yaw_rate": 0.0},
                source_provider=self.name,
                confidence=0.7,
            )
        if any(token in text for token in ("grasp", "pick", "place", "cube")):
            return StructuredCommand(
                robot=request.robot,
                command_type="manipulation",
                target={"skill": "pick_place", "object": "cube"},
                source_provider=self.name,
                confidence=0.64,
                notes=("The dashboard keeps this as dry-run structured intent.",),
            )
        return StructuredCommand(
            robot=request.robot,
            command_type="noop",
            target={},
            source_provider=self.name,
            confidence=0.3,
            notes=("Instruction was not mapped to a known robot skill.",),
        )


_PROVIDERS: dict[str, VLAProvider] = {
    RuleBasedVLAProvider.name: RuleBasedVLAProvider(),
}


def list_vla_providers() -> list[VLAProvider]:
    return [_PROVIDERS[name] for name in sorted(_PROVIDERS)]


def get_vla_provider(name: str) -> VLAProvider:
    try:
        return _PROVIDERS[name]
    except KeyError as exc:
        known = ", ".join(sorted(_PROVIDERS))
        raise ValueError(f"Unknown VLA provider '{name}'. Known providers: {known}") from exc
